//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Order_Status
    {
        public int ID { get; set; }
        public string Business_Unit { get; set; }
        public string YEAR { get; set; }
        public Nullable<double> Old_Orders_Amount { get; set; }
        public Nullable<double> Apr_Orders_Amount { get; set; }
        public Nullable<double> May_Orders_Amount { get; set; }
        public Nullable<double> Jun_Orders_Amount { get; set; }
        public Nullable<double> Jul_Orders_Amount { get; set; }
        public Nullable<double> Aug_Orders_Amount { get; set; }
        public Nullable<double> Sep_Orders_Amount { get; set; }
        public Nullable<double> Oct_Orders_Amount { get; set; }
        public Nullable<double> Nov_Orders_Amount { get; set; }
        public Nullable<double> Dec_Orders_Amount { get; set; }
        public Nullable<double> Jan_Orders_Amount { get; set; }
        public Nullable<double> Feb_Orders_Amount { get; set; }
        public Nullable<double> Mar_Orders_Amount { get; set; }
    }
}
