//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Balance
    {
        public int ID { get; set; }
        public string Business_Unit { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Total_Expanses_Amount { get; set; }
        public Nullable<decimal> Total_Received_Amount { get; set; }
        public Nullable<decimal> Balance_Amount { get; set; }
        public string Profit { get; set; }
    }
}
