//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Master_Client
    {
        public long ID { get; set; }
        public string Emp_Name { get; set; }
        public string Client_Name { get; set; }
        public string Email { get; set; }
        public string Reporting_Manager_at_client_place { get; set; }
        public string Shadow { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
    }
}
