//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingApplication.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Cust_Emp_Details
    {
        public long ID { get; set; }
        public string Cilent_ID { get; set; }
        public string Emp_Number { get; set; }
        public Nullable<System.DateTime> Cilent_Start_Date { get; set; }
        public Nullable<System.DateTime> Cilent_End_Date { get; set; }
    }
}
