//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillContexts.DBContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Billing_StagingEntities : DbContext
    {
        public Billing_StagingEntities()
            : base("name=Billing_StagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImSS_Balance> ImSS_Balance { get; set; }
        public virtual DbSet<ImSS_Business_Unit> ImSS_Business_Unit { get; set; }
        public virtual DbSet<ImSS_Category> ImSS_Category { get; set; }
        public virtual DbSet<ImSS_Client_List> ImSS_Client_List { get; set; }
        public virtual DbSet<ImSS_Currency_Rate> ImSS_Currency_Rate { get; set; }
        public virtual DbSet<ImSS_Domain> ImSS_Domain { get; set; }
        public virtual DbSet<ImSS_Expenses> ImSS_Expenses { get; set; }
        public virtual DbSet<ImSS_Invoice_Master> ImSS_Invoice_Master { get; set; }
        public virtual DbSet<ImSS_Location> ImSS_Location { get; set; }
        public virtual DbSet<ImSS_Master_Client> ImSS_Master_Client { get; set; }
        public virtual DbSet<ImSS_Master_Emp_List> ImSS_Master_Emp_List { get; set; }
        public virtual DbSet<ImSS_Master_Emp_List_c10406> ImSS_Master_Emp_List_c10406 { get; set; }
        public virtual DbSet<ImSS_Master_PO> ImSS_Master_PO { get; set; }
        public virtual DbSet<ImSS_Order_Status> ImSS_Order_Status { get; set; }
        public virtual DbSet<ImSS_Reporting_Head> ImSS_Reporting_Head { get; set; }
        public virtual DbSet<ImSS_Skills_Category> ImSS_Skills_Category { get; set; }
        public virtual DbSet<ImSS_Status> ImSS_Status { get; set; }
        public virtual DbSet<ImSS_TargetedVsActual> ImSS_TargetedVsActual { get; set; }
        public virtual DbSet<ImSS_Year> ImSS_Year { get; set; }
    }
}
