//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillContexts.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Master_PO
    {
        public int ID { get; set; }
        public string Client_Name { get; set; }
        public string Project_Name { get; set; }
        public string PO_Number { get; set; }
        public string Point_Of_Contact { get; set; }
        public string Mode_Of_Payment { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PO_StartDate { get; set; }
        public Nullable<System.DateTime> PO_EndDate { get; set; }
        public Nullable<double> PO_Initial_Amount { get; set; }
        public Nullable<int> PO_Duration { get; set; }
        public Nullable<double> PO_Renewed_Amount { get; set; }
        public Nullable<System.DateTime> PO_Renewed_Date { get; set; }
        public string Parent_PO { get; set; }
        public string PO_Status { get; set; }
        public Nullable<decimal> PO_Total_Amount_INR { get; set; }
        public Nullable<System.DateTime> PO_Close_Date { get; set; }
    }
}
