//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillContexts.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Domain
    {
        public int ID { get; set; }
        public string Domain_Name { get; set; }
    }
}
