//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillContexts.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_Expenses
    {
        public int ID { get; set; }
        public string Business_Unit { get; set; }
        public string YEAR { get; set; }
        public Nullable<decimal> Apr_Expenses { get; set; }
        public Nullable<decimal> May_Expenses { get; set; }
        public Nullable<decimal> Jun_Expenses { get; set; }
        public Nullable<decimal> Jul_Expenses { get; set; }
        public Nullable<decimal> Aug_Expenses { get; set; }
        public Nullable<decimal> Sep_Expenses { get; set; }
        public Nullable<decimal> Oct_Expenses { get; set; }
        public Nullable<decimal> Nov_Expenses { get; set; }
        public Nullable<decimal> Dec_Expenses { get; set; }
        public Nullable<decimal> Jan_Expenses { get; set; }
        public Nullable<decimal> Feb_Expenses { get; set; }
        public Nullable<decimal> Mar_Expenses { get; set; }
    }
}
