//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillContexts.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImSS_TargetedVsActual
    {
        public int ID { get; set; }
        public string Business_Unit { get; set; }
        public Nullable<double> Quarter1_TB { get; set; }
        public Nullable<double> Quarter1_AA { get; set; }
        public Nullable<double> Quarter2_TB { get; set; }
        public Nullable<double> Quarter2_AA { get; set; }
        public Nullable<double> Quarter3_TB { get; set; }
        public Nullable<double> Quarter3_AA { get; set; }
        public Nullable<double> Quarter4_TB { get; set; }
        public Nullable<double> Quarter4_AA { get; set; }
    }
}
